version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-86-22.compute-1.amazonaws.com
            database: desnmpkhi8toim
            ssl: true
            user: ybfgnrybhcukzf
            password: 3f81cfaf1732b8572646bd123337e882af26e15e1d59d31c2426c0212fa67cee
            rawAccess: true
            port: '5432'
            migrations: true